/* Forex Rulet - para birimi havuzu
 *
 * r  = 1 EUR kac birim eder (yaklasik, statik referans kurlar)
 * t  = taninirlik / risk kademesi
 *      1 = bilindik   2 = orta   3 = az bilinen   4 = asiri egzotik
 * d  = ondalik basamak (opsiyonel, yoksa kurdan tahmin edilir)
 *
 * Kurlar oyun icin dondurulmus yaklasik degerlerdir; canli piyasa verisi degildir.
 */
const CURRENCIES = [
  // ---------- Kademe 1 : herkesin bildigi ----------
  { c: 'USD', n: 'Amerikan Doları',      f: '🇺🇸', r: 1.08,   t: 1 },
  { c: 'GBP', n: 'İngiliz Sterlini',     f: '🇬🇧', r: 0.84,   t: 1 },
  { c: 'JPY', n: 'Japon Yeni',           f: '🇯🇵', r: 168,    t: 1 },
  { c: 'CHF', n: 'İsviçre Frangı',       f: '🇨🇭', r: 0.94,   t: 1 },
  { c: 'CAD', n: 'Kanada Doları',        f: '🇨🇦', r: 1.49,   t: 1 },
  { c: 'AUD', n: 'Avustralya Doları',    f: '🇦🇺', r: 1.66,   t: 1 },
  { c: 'CNY', n: 'Çin Yuanı',            f: '🇨🇳', r: 7.75,   t: 1 },
  { c: 'TRY', n: 'Türk Lirası',          f: '🇹🇷', r: 44.5,   t: 1 },
  { c: 'RUB', n: 'Rus Rublesi',          f: '🇷🇺', r: 92,     t: 1 },
  { c: 'INR', n: 'Hindistan Rupisi',     f: '🇮🇳', r: 94,     t: 1 },
  { c: 'BRL', n: 'Brezilya Reali',       f: '🇧🇷', r: 6.1,    t: 1 },
  { c: 'MXN', n: 'Meksika Pesosu',       f: '🇲🇽', r: 20.2,   t: 1 },
  { c: 'ZAR', n: 'Güney Afrika Randı',   f: '🇿🇦', r: 19.6,   t: 1 },
  { c: 'KRW', n: 'Güney Kore Wonu',      f: '🇰🇷', r: 1480,   t: 1 },
  { c: 'SEK', n: 'İsveç Kronu',          f: '🇸🇪', r: 11.2,   t: 1 },
  { c: 'NOK', n: 'Norveç Kronu',         f: '🇳🇴', r: 11.6,   t: 1 },
  { c: 'DKK', n: 'Danimarka Kronu',      f: '🇩🇰', r: 7.46,   t: 1 },
  { c: 'PLN', n: 'Polonya Zlotisi',      f: '🇵🇱', r: 4.27,   t: 1 },

  // ---------- Kademe 2 : adini duydugun ----------
  { c: 'CZK', n: 'Çek Korunası',         f: '🇨🇿', r: 25.1,   t: 2 },
  { c: 'HUF', n: 'Macar Forinti',        f: '🇭🇺', r: 396,    t: 2 },
  { c: 'RON', n: 'Romen Leyi',           f: '🇷🇴', r: 4.97,   t: 2 },
  { c: 'BGN', n: 'Bulgar Levası',        f: '🇧🇬', r: 1.96,   t: 2 },
  { c: 'ILS', n: 'İsrail Şekeli',        f: '🇮🇱', r: 3.95,   t: 2 },
  { c: 'AED', n: 'BAE Dirhemi',          f: '🇦🇪', r: 3.97,   t: 2 },
  { c: 'SAR', n: 'Suudi Riyali',         f: '🇸🇦', r: 4.05,   t: 2 },
  { c: 'QAR', n: 'Katar Riyali',         f: '🇶🇦', r: 3.93,   t: 2 },
  { c: 'THB', n: 'Tayland Bahtı',        f: '🇹🇭', r: 36.5,   t: 2 },
  { c: 'SGD', n: 'Singapur Doları',      f: '🇸🇬', r: 1.44,   t: 2 },
  { c: 'HKD', n: 'Hong Kong Doları',     f: '🇭🇰', r: 8.42,   t: 2 },
  { c: 'NZD', n: 'Yeni Zelanda Doları',  f: '🇳🇿', r: 1.80,   t: 2 },
  { c: 'MYR', n: 'Malezya Ringiti',      f: '🇲🇾', r: 4.75,   t: 2 },
  { c: 'IDR', n: 'Endonezya Rupiahı',    f: '🇮🇩', r: 17600,  t: 2 },
  { c: 'PHP', n: 'Filipin Pesosu',       f: '🇵🇭', r: 61.5,   t: 2 },
  { c: 'VND', n: 'Vietnam Dongu',        f: '🇻🇳', r: 27800,  t: 2 },
  { c: 'EGP', n: 'Mısır Lirası',         f: '🇪🇬', r: 53,     t: 2 },
  { c: 'NGN', n: 'Nijerya Nairası',      f: '🇳🇬', r: 1660,   t: 2 },
  { c: 'ARS', n: 'Arjantin Pesosu',      f: '🇦🇷', r: 1250,   t: 2 },
  { c: 'CLP', n: 'Şili Pesosu',          f: '🇨🇱', r: 1020,   t: 2 },
  { c: 'COP', n: 'Kolombiya Pesosu',     f: '🇨🇴', r: 4400,   t: 2 },
  { c: 'PKR', n: 'Pakistan Rupisi',      f: '🇵🇰', r: 303,    t: 2 },
  { c: 'UAH', n: 'Ukrayna Grivnası',     f: '🇺🇦', r: 45,     t: 2 },
  { c: 'ISK', n: 'İzlanda Kronu',        f: '🇮🇸', r: 149,    t: 2 },

  // ---------- Kademe 3 : az bilinen ----------
  { c: 'PEN', n: 'Peru Solu',            f: '🇵🇪', r: 4.0,    t: 3 },
  { c: 'KZT', n: 'Kazak Tengesi',        f: '🇰🇿', r: 560,    t: 3 },
  { c: 'MAD', n: 'Fas Dirhemi',          f: '🇲🇦', r: 10.8,   t: 3 },
  { c: 'TND', n: 'Tunus Dinarı',         f: '🇹🇳', r: 3.35,   t: 3, d: 3 },
  { c: 'DZD', n: 'Cezayir Dinarı',       f: '🇩🇿', r: 145,    t: 3 },
  { c: 'JOD', n: 'Ürdün Dinarı',         f: '🇯🇴', r: 0.77,   t: 3, d: 3 },
  { c: 'KWD', n: 'Kuveyt Dinarı',        f: '🇰🇼', r: 0.33,   t: 3, d: 3 },
  { c: 'BHD', n: 'Bahreyn Dinarı',       f: '🇧🇭', r: 0.41,   t: 3, d: 3 },
  { c: 'OMR', n: 'Umman Riyali',         f: '🇴🇲', r: 0.42,   t: 3, d: 3 },
  { c: 'LKR', n: 'Sri Lanka Rupisi',     f: '🇱🇰', r: 320,    t: 3 },
  { c: 'BDT', n: 'Bangladeş Takası',     f: '🇧🇩', r: 132,    t: 3 },
  { c: 'NPR', n: 'Nepal Rupisi',         f: '🇳🇵', r: 150,    t: 3 },
  { c: 'MMK', n: 'Myanmar Kyatı',        f: '🇲🇲', r: 2270,   t: 3 },
  { c: 'KHR', n: 'Kamboçya Rieli',         f: '🇰🇭', r: 4350,   t: 3 },
  { c: 'LAK', n: 'Laos Kipi',            f: '🇱🇦', r: 23500,  t: 3 },
  { c: 'MNT', n: 'Moğol Tugriki',        f: '🇲🇳', r: 3800,   t: 3 },
  { c: 'UZS', n: 'Özbek Somu',           f: '🇺🇿', r: 13800,  t: 3 },
  { c: 'GEL', n: 'Gürcü Larisi',         f: '🇬🇪', r: 2.95,   t: 3 },
  { c: 'AMD', n: 'Ermeni Dramı',         f: '🇦🇲', r: 418,    t: 3 },
  { c: 'AZN', n: 'Azerbaycan Manatı',    f: '🇦🇿', r: 1.84,   t: 3 },
  { c: 'RSD', n: 'Sırp Dinarı',          f: '🇷🇸', r: 117,    t: 3 },
  { c: 'MKD', n: 'Makedon Denarı',       f: '🇲🇰', r: 61.5,   t: 3 },
  { c: 'ALL', n: 'Arnavut Leki',         f: '🇦🇱', r: 96,     t: 3 },
  { c: 'MDL', n: 'Moldova Leyi',         f: '🇲🇩', r: 19.5,   t: 3 },
  { c: 'BAM', n: 'Bosna Markası',        f: '🇧🇦', r: 1.96,   t: 3 },
  { c: 'BYN', n: 'Belarus Rublesi',      f: '🇧🇾', r: 3.55,   t: 3 },
  { c: 'KES', n: 'Kenya Şilini',         f: '🇰🇪', r: 140,    t: 3 },
  { c: 'GHS', n: 'Gana Cedisi',          f: '🇬🇭', r: 16.5,   t: 3 },
  { c: 'TZS', n: 'Tanzanya Şilini',      f: '🇹🇿', r: 2850,   t: 3 },
  { c: 'UGX', n: 'Uganda Şilini',        f: '🇺🇬', r: 3950,   t: 3 },
  { c: 'ETB', n: 'Etiyopya Birri',       f: '🇪🇹', r: 145,    t: 3 },
  { c: 'MUR', n: 'Mauritius Rupisi',     f: '🇲🇺', r: 50,     t: 3 },
  { c: 'BWP', n: 'Botsvana Pulası',      f: '🇧🇼', r: 14.8,   t: 3 },
  { c: 'NAD', n: 'Namibya Doları',       f: '🇳🇦', r: 19.6,   t: 3 },
  { c: 'BND', n: 'Brunei Doları',        f: '🇧🇳', r: 1.44,   t: 3 },
  { c: 'MVR', n: 'Maldiv Rufiyaası',     f: '🇲🇻', r: 16.7,   t: 3 },
  { c: 'FJD', n: 'Fiji Doları',          f: '🇫🇯', r: 2.45,   t: 3 },
  { c: 'JMD', n: 'Jamaika Doları',       f: '🇯🇲', r: 170,    t: 3 },
  { c: 'TTD', n: 'Trinidad Doları',      f: '🇹🇹', r: 7.4,    t: 3 },
  { c: 'DOP', n: 'Dominik Pesosu',       f: '🇩🇴', r: 66,     t: 3 },
  { c: 'GTQ', n: 'Guatemala Ketzali',    f: '🇬🇹', r: 8.35,   t: 3 },
  { c: 'CRC', n: 'Kosta Rika Kolonu',    f: '🇨🇷', r: 550,    t: 3 },
  { c: 'BOB', n: 'Bolivya Bolivyanosu',  f: '🇧🇴', r: 7.5,    t: 3 },
  { c: 'PYG', n: 'Paraguay Guaranisi',   f: '🇵🇾', r: 8500,   t: 3 },
  { c: 'UYU', n: 'Uruguay Pesosu',       f: '🇺🇾', r: 43,     t: 3 },
  { c: 'HNL', n: 'Honduras Lempirası',   f: '🇭🇳', r: 27,     t: 3 },
  { c: 'NIO', n: 'Nikaragua Kordobası',  f: '🇳🇮', r: 39.7,   t: 3 },
  { c: 'IQD', n: 'Irak Dinarı',          f: '🇮🇶', r: 1420,   t: 3 },
  { c: 'LYD', n: 'Libya Dinarı',         f: '🇱🇾', r: 5.25,   t: 3, d: 3 },
  { c: 'AFN', n: 'Afgan Afganisi',       f: '🇦🇫', r: 76,     t: 3 },
  { c: 'TJS', n: 'Tacik Somonisi',       f: '🇹🇯', r: 11.6,   t: 3 },
  { c: 'TMT', n: 'Türkmen Manatı',       f: '🇹🇲', r: 3.80,   t: 3 },
  { c: 'KGS', n: 'Kırgız Somu',          f: '🇰🇬', r: 94,     t: 3 },
  { c: 'BTN', n: 'Butan Ngultrumu',      f: '🇧🇹', r: 94,     t: 3 },

  // ---------- Kademe 4 : asiri egzotik ----------
  { c: 'XOF', n: 'Batı Afrika CFA Frangı',  f: '🌍', r: 655.96, t: 4 },
  { c: 'XAF', n: 'Orta Afrika CFA Frangı',  f: '🌍', r: 655.96, t: 4 },
  { c: 'XPF', n: 'CFP Frangı',              f: '🇵🇫', r: 119.33, t: 4 },
  { c: 'RWF', n: 'Ruanda Frangı',           f: '🇷🇼', r: 1560,   t: 4 },
  { c: 'BIF', n: 'Burundi Frangı',          f: '🇧🇮', r: 3210,   t: 4 },
  { c: 'KMF', n: 'Komor Frangı',            f: '🇰🇲', r: 492,    t: 4 },
  { c: 'DJF', n: 'Cibuti Frangı',           f: '🇩🇯', r: 192,    t: 4 },
  { c: 'CDF', n: 'Kongo Frangı',            f: '🇨🇩', r: 3100,   t: 4 },
  { c: 'GNF', n: 'Gine Frangı',             f: '🇬🇳', r: 9400,   t: 4 },
  { c: 'ERN', n: 'Eritre Nakfası',          f: '🇪🇷', r: 16.2,   t: 4 },
  { c: 'SOS', n: 'Somali Şilini',           f: '🇸🇴', r: 618,    t: 4 },
  { c: 'SSP', n: 'Güney Sudan Lirası',      f: '🇸🇸', r: 4900,   t: 4 },
  { c: 'SDG', n: 'Sudan Lirası',            f: '🇸🇩', r: 650,    t: 4 },
  { c: 'ZMW', n: 'Zambiya Kvaçası',        f: '🇿🇲', r: 27.5,   t: 4 },
  { c: 'MWK', n: 'Malavi Kvaçası',         f: '🇲🇼', r: 1880,   t: 4 },
  { c: 'MZN', n: 'Mozambik Metikali',       f: '🇲🇿', r: 69,     t: 4 },
  { c: 'AOA', n: 'Angola Kvanzası',         f: '🇦🇴', r: 990,    t: 4 },
  { c: 'GMD', n: 'Gambiya Dalasisi',        f: '🇬🇲', r: 78,     t: 4 },
  { c: 'SLE', n: 'Sierra Leone Leonu',      f: '🇸🇱', r: 24.5,   t: 4 },
  { c: 'LRD', n: 'Liberya Doları',          f: '🇱🇷', r: 205,    t: 4 },
  { c: 'CVE', n: 'Yeşil Burun Eskudosu',    f: '🇨🇻', r: 110.27, t: 4 },
  { c: 'STN', n: 'Sao Tome Dobrası',        f: '🇸🇹', r: 24.5,   t: 4 },
  { c: 'MGA', n: 'Madagaskar Ariarisi',     f: '🇲🇬', r: 4900,   t: 4 },
  { c: 'SCR', n: 'Seyşel Rupisi',           f: '🇸🇨', r: 15.5,   t: 4 },
  { c: 'MRU', n: 'Moritanya Ugiyası',       f: '🇲🇷', r: 43,     t: 4 },
  { c: 'LSL', n: 'Lesotho Lotisi',          f: '🇱🇸', r: 19.6,   t: 4 },
  { c: 'SZL', n: 'Esvatini Lilangenisi',    f: '🇸🇿', r: 19.6,   t: 4 },
  { c: 'PGK', n: 'Papua Yeni Gine Kinası',  f: '🇵🇬', r: 4.4,    t: 4 },
  { c: 'SBD', n: 'Solomon Adaları Doları',  f: '🇸🇧', r: 9.2,    t: 4 },
  { c: 'VUV', n: 'Vanuatu Vatusu',          f: '🇻🇺', r: 131,    t: 4 },
  { c: 'WST', n: 'Samoa Talası',            f: '🇼🇸', r: 3.0,    t: 4 },
  { c: 'TOP', n: 'Tonga Pangası',           f: '🇹🇴', r: 2.6,    t: 4 },
  { c: 'SRD', n: 'Surinam Doları',          f: '🇸🇷', r: 41,     t: 4 },
  { c: 'GYD', n: 'Guyana Doları',           f: '🇬🇾', r: 226,    t: 4 },
  { c: 'HTG', n: 'Haiti Gurdu',             f: '🇭🇹', r: 142,    t: 4 },
  { c: 'CUP', n: 'Küba Pesosu',             f: '🇨🇺', r: 26,     t: 4 },
  { c: 'BSD', n: 'Bahama Doları',           f: '🇧🇸', r: 1.08,   t: 4 },
  { c: 'BZD', n: 'Belize Doları',           f: '🇧🇿', r: 2.18,   t: 4 },
  { c: 'BBD', n: 'Barbados Doları',         f: '🇧🇧', r: 2.16,   t: 4 },
  { c: 'XCD', n: 'Doğu Karayip Doları',     f: '🇦🇬', r: 2.92,   t: 4 },
  { c: 'AWG', n: 'Aruba Florini',           f: '🇦🇼', r: 1.94,   t: 4 },
  { c: 'ANG', n: 'Antil Florini',           f: '🇨🇼', r: 1.94,   t: 4 },
  { c: 'PAB', n: 'Panama Balboası',         f: '🇵🇦', r: 1.08,   t: 4 },
  { c: 'KYD', n: 'Cayman Adaları Doları',   f: '🇰🇾', r: 0.90,   t: 4 },
  { c: 'BMD', n: 'Bermuda Doları',          f: '🇧🇲', r: 1.08,   t: 4 },
  { c: 'FKP', n: 'Falkland Sterlini',       f: '🇫🇰', r: 0.84,   t: 4 },
  { c: 'GIP', n: 'Cebelitarık Sterlini',    f: '🇬🇮', r: 0.84,   t: 4 },
  { c: 'SHP', n: 'Saint Helena Sterlini',   f: '🇸🇭', r: 0.84,   t: 4 },
  { c: 'YER', n: 'Yemen Riyali',            f: '🇾🇪', r: 270,    t: 4 },
  { c: 'SYP', n: 'Suriye Lirası',           f: '🇸🇾', r: 14000,  t: 4 },
  { c: 'IRR', n: 'İran Riyali',             f: '🇮🇷', r: 45500,  t: 4 },
  { c: 'KPW', n: 'Kuzey Kore Wonu',         f: '🇰🇵', r: 972,    t: 4 },
  { c: 'ZWG', n: 'Zimbabve Altın Birimi',   f: '🇿🇼', r: 28,     t: 4 }
];

/** EUR "sanal" para birimi olarak da kullanilir (baslangic parasi). */
const EUR = { c: 'EUR', n: 'Euro', f: '🇪🇺', r: 1, t: 0 };

const CUR_BY_CODE = (() => {
  const m = { EUR: EUR };
  for (const x of CURRENCIES) m[x.c] = x;
  return m;
})();

const TIER_INFO = {
  0: { label: 'Referans',    cls: 'tier-0', spread: 0.00, med: 1.00 },
  1: { label: 'Düşük risk',  cls: 'tier-1', spread: 0.11, med: 0.99 },
  2: { label: 'Orta risk',   cls: 'tier-2', spread: 0.24, med: 0.99 },
  3: { label: 'Yüksek risk', cls: 'tier-3', spread: 0.42, med: 0.97 },
  4: { label: 'Çılgın risk', cls: 'tier-4', spread: 0.66, med: 0.94 }
};
